name: tracoin
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'certifi=2016.2.28=py36_0'
- !!python/unicode
  'openssl=1.0.2l=0'
- !!python/unicode
  'pip=9.0.1=py36_1'
- !!python/unicode
  'python=3.6.2=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=36.4.0=py36_1'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py36_0'
- !!python/unicode
  'xz=5.2.3=0'
- !!python/unicode
  'zlib=1.2.11=0'
- pip:
  - mccabe==0.6.1
  - numpy==1.14.0
  - pandas==0.22.0
  - psycopg2==2.7.3.2
  - python-dateutil==2.6.1
  - pytz==2017.3
  - requests==2.14.2
  - six==1.11.0
  - sqlalchemy==1.2.1
  - virtualenv-clone==0.2.6
